// Karaoke-style line-by-line lyrics (time in seconds)
const syncedLyrics = {
    0: [
        { "time": 0, "text": "You're glowing" },
        { "time": 5, "text": "You colour and fracture the light" },
        { "time": 8, "text": "You can't help but shine" },
        { "time": 12, "text": "And I know that" },
        { "time": 13, "text": "You carry the world on your back" },
        { "time": 17, "text": "But look at you tonight" },

        { "time": 21, "text": "The lights, your face, your eyes" },
        { "time": 25, "text": "Exploding like fireworks in the sky" },
        { "time": 29, "text": "Sapphire" },

        { "time": 32, "text": "Touching on your body while you're pushing on me" },
        { "time": 37, "text": "Don't you end the party, I could do this all week" },
        { "time": 42, "text": "We'll be dancing till the morning, go to bed, we won't sleep" },
        { "time": 47, "text": "ਚਮ-ਚਮ ਚਮਕੇ ਸਿਤਾਰੇ ਵਰਗੀ (Sapphire)" },

        { "time": 52, "text": "Touching on your body while you're pushing on me" },
        { "time": 56, "text": "Don't you end the party, I could do this all week" },
        { "time": 61, "text": "We'll be dancing till the morning, go to bed, we won't sleep" },
        { "time": 66, "text": "ਚਮ-ਚਮ ਚਮਕੇ ਸਿਤਾਰੇ ਵਰਗੀ" },

        { "time": 71, "text": "Look what we found, Karma reached out" },
        { "time": 75, "text": "Into our hearts and pulled us to our feet now" },
        { "time": 79, "text": "You know, the truth is we could disappear" },
        { "time": 83, "text": "Anywhere, as long as I got you there" },
        { "time": 87, "text": "When the sun dies, till the day shines" },
        { "time": 91, "text": "When I'm with you, there's not enough time" },
        { "time": 95, "text": "You are my spring flower, watching you bloom, wow" },
        { "time": 100, "text": "We are surrounded, but I can only see" },

        { "time": 104, "text": "The lights, your face, your eyes" },
        { "time": 108, "text": "Exploding like fireworks in the sky" },
        { "time": 112, "text": "Sapphire" },

        { "time": 115, "text": "Touching on your body while you're pushing on me" },
        { "time": 120, "text": "Don't you end the party, I could do this all week" },
        { "time": 125, "text": "We'll be dancing till the morning, go to bed, we won't sleep" },
        { "time": 130, "text": "ਚਮ-ਚਮ ਚਮਕੇ ਸਿਤਾਰੇ ਵਰਗੀ (Sapphire)" },

        { "time": 135, "text": "Touching on your body while you're pushing on me" },
        { "time": 140, "text": "Don't you end the party, I could do this all week" },
        { "time": 145, "text": "We'll be dancing till the morning, go to bed, we won't sleep" },
        { "time": 150, "text": "ਚਮ-ਚਮ ਚਮਕੇ ਸਿਤਾਰੇ ਵਰਗੀ (Sapphire)" },

        { "time": 155, "text": "मेहरूनी दो नैन लुभाए" },
        { "time": 158, "text": "चाँदनी चम-चम चमकाए You're glowing" },
        { "time": 162, "text": "ਨੂਰ ਦਾ ਮੈਨੂੰ ਘੁੱਟ ਪਿਲਾਏ" },
        { "time": 166, "text": "ਜਿੰਦੜੀ ਬਣ ਜਾਏ" },
        { "time": 170, "text": "You're glowing ਅੰਬਰਾਂ ਦੀ ਤੂੰ ਝਾਲਰ ਪਾਏ" },
        { "time": 174, "text": "You colour and fracture the light ਬਦਲ਼ਾਂ ਦੇ ਲੱਠੇ ਸੂਟ ਬਣਾਏ" },
        { "time": 179, "text": "But look at you tonight ਕਿਰਣਾਂ ਨੂੰ ਰੰਗ-ਰੂਪ ਛਡਾਏ" },
        { "time": 184, "text": "ਮੋਰਣੀ ਬਣ ਜਾਏ Sapphire" },
        { "time": 188, "text": "ਪਲਕਾਂ ਉਠਾਵਤੇ ਹਨੇਰੇ ਘਟਦੇ" },
        { "time": 192, "text": "ਉਂਗਲਾ’ਚ ਪਾਕੇ ਤੂੰ ਧਨਕ ਫਿਰਦੀ" },
        { "time": 196, "text": "ਕਿਵੇਂ ਰੱਬ ਨੇ ਦੋ ਨੈਣਾਂ ਉੱਤੇ ਨੀਲਮ ਜੜੇ?" },
        { "time": 200, "text": "ਚਮ-ਚਮ ਚਮਕੇ ਸਿਤਾਰੇ ਵਰਗੀ (Sapphire)" },

        { "time": 205, "text": "Touching on your body while you're pushing on me" },
        { "time": 210, "text": "Don't you end the party, I could do this all week" },
        { "time": 215, "text": "We'll be dancing till the morning, go to bed, we won't sleep" },
        { "time": 220, "text": "ਚਮ-ਚਮ ਚਮਕੇ ਸਿਤਾਰੇ ਵਰਗੀ (Sapphire)" },

        { "time": 225, "text": "Touching on your body while you're pushing on me (The lights, your face, your eyes)" },
        { "time": 230, "text": "Don't you end the party, I could do this all week (Exploding)" },
        { "time": 235, "text": "We'll be dancing till the morning, go to bed, we won't sleep (Like fireworks in the sky)" },
        { "time": 240, "text": "ਚਮ-ਚਮ ਚਮਕੇ ਸਿਤਾਰੇ ਵਰਗੀ (Sapphire)" },

        { "time": 245, "text": "Touching on your body while you're pushing on me (The lights, your face, your eyes)" },
        { "time": 250, "text": "Don't you end the party, I could do this all week (Exploding)" },
        { "time": 255, "text": "We'll be dancing till the morning, go to bed, we won't sleep (Like fireworks in the sky)" },
        { "time": 260, "text": "ਚਮ-ਚਮ ਚਮਕੇ ਸਿਤਾਰੇ ਵਰਗੀ (Sapphire)" }
    ],
    1: [
        { time: 19, text: "Tell me what you really like" },
        { time: 22, text: "Baby I can take my time" },
        { time: 24, text: "We don't ever have to fight" },
        { time: 27, text: "Just take it step by step" },
        { time: 29, text: "I can see it in your eyes" },
        { time: 32, text: "‘Cause they never tell me lies" },
        { time: 35, text: "I can feel that body shake" },
        { time: 37, text: "And the heat between your legs" },

        { time: 40, text: "You've been scared of love" },
        { time: 42, text: "And what it did to you" },
        { time: 45, text: "You don't have to run" },
        { time: 47, text: "I know what you've been through" },
        { time: 50, text: "Just a simple touch" },
        { time: 53, text: "And it can set you free" },
        { time: 55, text: "We don't have to rush" },
        { time: 58, text: "When you're alone with me" },

        { time: 60, text: "I feel it coming" },
        { time: 63, text: "I feel it coming babe" },
        { time: 66, text: "I feel it coming" },
        { time: 68, text: "I feel it coming babe" },
        { time: 71, text: "I feel it coming" },
        { time: 73, text: "I feel it coming babe" },
        { time: 76, text: "I feel it coming" },
        { time: 78, text: "I feel it coming babe" },

        { time: 81, text: "You are not the single type" },
        { time: 84, text: "So baby this the perfect time" },
        { time: 86, text: "I'm just trying to get you high" },
        { time: 89, text: "And faded off this touch" },
        { time: 91, text: "You don't need a lonely night" },
        { time: 94, text: "So baby I can make it right" },
        { time: 96, text: "You just got to let me try" },
        { time: 99, text: "To give you what you want" },

        { time: 102, text: "You've been scared of love" },
        { time: 104, text: "And what it did to you" },
        { time: 107, text: "You don't have to run" },
        { time: 109, text: "I know what you've been through" },
        { time: 112, text: "Just a simple touch" },
        { time: 115, text: "And it can set you free" },
        { time: 117, text: "We don't have to rush" },
        { time: 120, text: "When you're alone with me" },

        { time: 122, text: "I feel it coming" },
        { time: 125, text: "I feel it coming babe" },
        { time: 128, text: "I feel it coming" },
        { time: 130, text: "I feel it coming babe" },
        { time: 133, text: "I feel it coming" },
        { time: 135, text: "I feel it coming babe" },
        { time: 138, text: "I feel it coming" },
        { time: 140, text: "I feel it coming babe" },

        { time: 143, text: "I feel it coming" },
        { time: 145, text: "I feel it coming babe" },

        { time: 148, text: "You've been scared of love" },
        { time: 150, text: "And what it did to you" },
        { time: 153, text: "You don't have to run" },
        { time: 155, text: "I know what you've been through" },
        { time: 158, text: "Just a simple touch" },
        { time: 161, text: "And it can set you free" },
        { time: 163, text: "We don't have to rush" },
        { time: 166, text: "When you're alone with me" },

        { time: 168, text: "I feel it coming" },
        { time: 171, text: "I feel it coming babe" },
        { time: 174, text: "I feel it coming" },
        { time: 176, text: "I feel it coming babe" }
    ],

    3: [
        { time: 27.45, text: "Ay, Fonsi, DY" },
        { time: 29.80, text: "Oh‑oh, oh no, oh no" },
        { time: 31.50, text: "Hey yeah" },
        { time: 33.20, text: "Sí, sabes que ya llevo un rato mirándote" },
        { time: 37.35, text: "Tengo que bailar contigo hoy (DY)" },
        { time: 41.10, text: "Vi que tu mirada ya estaba llamándome" },
        { time: 44.85, text: "Muéstrame el camino que yo voy (Oh)" },
        { time: 48.50, text: "Tú, tú eres el imán y yo soy el metal" },
        { time: 52.15, text: "Me voy acercando y voy armando el plan" },
        { time: 55.00, text: "Solo con pensarlo se acelera el pulso (Oh yeah)" },
        { time: 58.75, text: "Ya, ya me está gustando más de lo normal" },
        { time: 62.40, text: "Todos mis sentidos van pidiendo más" },
        { time: 66.10, text: "Esto hay que tomarlo sin ningún apuro" },
        { time: 68.75, text: "Despacito" },
        { time: 70.25, text: "Quiero respirar tu cuello despacito" },
        { time: 73.00, text: "Deja que te diga cosas al oído" },
        { time: 76.40, text: "Para que te acuerdes si no estás conmigo" },
        { time: 80.10, text: "Despacito" },
        { time: 81.60, text: "Quiero desnudarte a besos despacito" },
        { time: 84.30, text: "Firmar las paredes de tu laberinto" },
        { time: 87.90, text: "Y hacer de tu cuerpo todo un manuscrito" },
        { time: 91.70, text: "(Sube, sube, sube, sube, sube)" },
        { time: 93.50, text: "Quiero ver bailar tu pelo, quiero ser tu ritmo" },
        { time: 97.00, text: "Que le enseñes a mi boca tus lugares favoritos" },
        { time: 100.50, text: "(Favoritos, favoritos baby)" },
        { time: 102.30, text: "Déjame sobrepasar tus zonas de peligro" },
        { time: 105.80, text: "Hasta provocar tus gritos" },
        { time: 108.50, text: "Y que olvides tu apellido" },
        { time: 111.00, text: "Despacito" },
        { time: 114.00, text: "This is how we do it down in Puerto Rico" },
        { time: 117.20, text: "I just wanna hear you screaming, '¡Ay, Bendito!'" },
        { time: 122.00, text: "I can move forever cuando esté contigo" },
        { time: 125.40, text: "Bailando que tu boca con la mía" },
        { time: 128.80, text: "Tu cuerpo y el mío llenando el vacío" },
        { time: 132.20, text: "Subiendo y bajando (subiendo y bajando)" },
        { time: 135.50, text: "Eso es tan bonito, quiero ver tu pelo subir y bajar" },
        { time: 139.10, text: "Quiero abrazarte despacito" },
        { time: 141.90, text: "Firmar las paredes de tu laberinto" },
        { time: 145.40, text: "Y hacer de tu cuerpo todo un manuscrito (sube, sube, sube)" },
        { time: 148.00, text: "Quiero ver bailar tu pelo, quiero ser tu ritmo" },
        { time: 151.30, text: "Que le enseñes a mi boca tus lugares favoritos" },
        { time: 154.80, text: "(Favoritos, favoritos baby)" },
        { time: 157.50, text: "Déjame sobrepasar tus zonas de peligro" },
        { time: 160.80, text: "Hasta provocar tus gritos" },
        { time: 163.50, text: "Y que olvides tu apellido" },
        { time: 166.00, text: "Despacito" },
        { time: 169.00, text: "Despacito" }
    ]









};